set(_CATKIN_CURRENT_PACKAGE "pcl_tutorials")
set(pcl_tutorials_VERSION "0.0.0")
set(pcl_tutorials_MAINTAINER "amsl <amsl@todo.todo>")
set(pcl_tutorials_PACKAGE_FORMAT "1")
set(pcl_tutorials_BUILD_DEPENDS "laser_geometry" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(pcl_tutorials_BUILD_EXPORT_DEPENDS "laser_geometry" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(pcl_tutorials_BUILDTOOL_DEPENDS "catkin")
set(pcl_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_tutorials_EXEC_DEPENDS "laser_geometry" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(pcl_tutorials_RUN_DEPENDS "laser_geometry" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(pcl_tutorials_TEST_DEPENDS )
set(pcl_tutorials_DOC_DEPENDS )
set(pcl_tutorials_DEPRECATED "")